[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "onnxruntime>=1.21.1",
    "python-multipart>=0.0.20",
    "rembg>=2.0.65",
    "uvicorn>=0.34.2",
]
